#!/usr/bin/env python3
"""Generate the .lproj/Localizable.strings files from translations.py."""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from translations import T

ROOT = pathlib.Path(__file__).parent.parent / "Sources/VideoGen/Resources/Localizations"
LANGS = ["en", "zh-Hant", "zh-Hans", "de", "ar"]

def esc(value):
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

missing = 0
for lang in LANGS:
    lines = ['/* Generated by Scripts/build_strings.py — edit translations.py */', '']
    for key in sorted(T):
        entry = T[key]
        value = entry.get(lang)
        if not value:
            missing += 1
            value = entry["en"]
        if entry.get("note"):
            lines.append(f'/* {entry["note"]} */')
        lines.append(f'"{key}" = "{esc(value)}";')
        lines.append('')
    target = ROOT / f"{lang}.lproj" / "Localizable.strings"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines), encoding="utf-8")
    print(f"  {lang:8s} {len(T)} keys -> {target.relative_to(ROOT.parent.parent.parent.parent)}")
if missing:
    print(f"  WARNING: {missing} missing translations fell back to English")
