#!/usr/bin/env python3
"""Generate the .lproj/Localizable.strings files from translations.py.

Also writes a JSON catalogue of every key, every translation and every note, for
the Debug ▸ Localisations (i18n) window to read at runtime. The .strings files
cannot serve that purpose: each holds one language, and the notes become C
comments that nothing can read back.

The rendering lives in functions because Scripts/check_translations.py calls
them to work out what the files on disk *should* contain. If the checker had its
own copy of this logic the two could disagree, and the check would be worthless
exactly when it mattered.
"""
import json, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from translations import GLOSSARY, LANGS, SOURCE_LANG, T, note_of, value

ROOT = pathlib.Path(__file__).parent.parent / "Sources/Halation/Resources/Localizations"
CATALOG = ROOT.parent / "translation-catalog.json"

# LANGS comes from translations.py, which is where a new language is added. It
# used to be declared here as well, which meant the list a translator edited and
# the list the build iterated could disagree.


def esc(value):
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def render_strings(lang, table=T):
    """The exact contents of one .lproj/Localizable.strings.

    A key with no translation for this language emits the English, so a
    part-translated language still produces a complete file and the app never
    falls through to showing a raw key.
    """
    lines = ['/* Generated by Scripts/build_strings.py — edit translations.py */', '']
    for key in sorted(table):
        note, level = note_of(key)
        if note:
            lines.append(f'/* {"WARNING: " if level == "warning" else ""}{note} */')
        if lang != SOURCE_LANG and not table[key]["values"].get(lang):
            lines.append(f'/* Untranslated — showing {SOURCE_LANG}. */')
        lines.append(f'"{key}" = "{esc(value(key, lang))}";')
        lines.append('')
    return "\n".join(lines)


def render_catalog(table=T):
    """The exact contents of translation-catalog.json."""
    catalog = {
        "languages": LANGS,
        # Carried in the same file the inspector already reads, so the app can
        # show the glossary beside the strings it governs without a second
        # resource to keep in step.
        "glossary": GLOSSARY,
        "entries": [
            {
                "key": key,
                # Deliberately the raw values, not the English fallback: the
                # inspector's job is to show which languages are still missing,
                # and filling the gaps in would hide exactly that.
                "values": {lang: table[key]["values"].get(lang) or "" for lang in LANGS},
                "note": note_of(key)[0],
                "level": note_of(key)[1],
            }
            for key in sorted(table)
        ],
    }
    return json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=False) + "\n"


def missing_translations(table=T):
    """(key, language) for everything still falling back to English."""
    return [(key, lang) for key in sorted(table) for lang in LANGS
            if not table[key]["values"].get(lang)]


def main():
    for lang in LANGS:
        target = ROOT / f"{lang}.lproj" / "Localizable.strings"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(render_strings(lang), encoding="utf-8")
        print(f"  {lang:8s} {len(T)} keys -> {target.relative_to(ROOT.parent.parent.parent.parent)}")

    CATALOG.write_text(render_catalog(), encoding="utf-8")
    noted = sum(1 for k in T if note_of(k)[0])
    warned = sum(1 for k in T if note_of(k)[1] == "warning")
    print(f"  catalog  {len(T)} keys, {noted} notes ({warned} warnings) -> {CATALOG.name}")

    gaps = missing_translations()
    if gaps:
        by_lang = {}
        for _, lang in gaps:
            by_lang[lang] = by_lang.get(lang, 0) + 1
        summary = ", ".join(f"{lang} {count}" for lang, count in sorted(by_lang.items()))
        print(f"  {len(gaps)} untranslated, showing English ({summary})")


if __name__ == "__main__":
    main()
