#!/usr/bin/env python3
"""Generate the .lproj/Localizable.strings files from translations.py.

Also writes a JSON catalogue of every key, every translation and every note, for
the Debug ▸ Localisations (i18n) window to read at runtime. The .strings files
cannot serve that purpose: each holds one language, and the notes become C\ncomments that nothing can read back.
"""
import json, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from translations import T

ROOT = pathlib.Path(__file__).parent.parent / "Sources/Halation/Resources/Localizations"
LANGS = ["en", "zh-Hant", "zh-Hans", "de", "ar"]

def esc(value):
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

missing = 0
for lang in LANGS:
    lines = ['/* Generated by Scripts/build_strings.py — edit translations.py */', '']
    for key in sorted(T):
        entry = T[key]
        value = entry.get(lang)
        if not value:
            missing += 1
            value = entry["en"]
        if entry.get("note"):
            prefix = "WARNING: " if entry.get("level") == "warning" else ""
            lines.append(f'/* {prefix}{entry["note"]} */')
        lines.append(f'"{key}" = "{esc(value)}";')
        lines.append('')
    target = ROOT / f"{lang}.lproj" / "Localizable.strings"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines), encoding="utf-8")
    print(f"  {lang:8s} {len(T)} keys -> {target.relative_to(ROOT.parent.parent.parent.parent)}")
# The catalogue the in-app inspector reads. Sorted so the file is stable in
# diffs and a review shows only what actually changed.
catalog = {
    "languages": LANGS,
    "entries": [
        {
            "key": key,
            "values": {lang: T[key].get(lang) or "" for lang in LANGS},
            "note": T[key].get("note") or "",
            "level": T[key].get("level") or "info",
        }
        for key in sorted(T)
    ],
}
catalog_path = ROOT.parent / "translation-catalog.json"
catalog_path.write_text(
    json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=False) + "\n",
    encoding="utf-8")
noted = sum(1 for e in catalog["entries"] if e["note"])
warned = sum(1 for e in catalog["entries"] if e["level"] == "warning")
print(f"  catalog  {len(T)} keys, {noted} notes ({warned} warnings) -> {catalog_path.name}")

if missing:
    print(f"  WARNING: {missing} missing translations fell back to English")
